runtime: nodejs16
env_variables:
  NODE_ENV: "production"
default_expiration: "1d 12h"

handlers:
- url: /static/media
  secure: always
  static_dir: static/media
  default_expiration: "1d 12h"

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

entrypoint: npm run gcp-start
